### PR TITLE
node: client and consumer

### PR DESCRIPTION
**Pull request by c1tt1**
Added client and consumer services.

Please let me know what has to done besides `mux`.
Thank you

### CODE REVIEW

**Comment by celrenheit** [comment]
This looks good to me, could you provide an example of how the client should be used ?
The port should be a parameter to the constructor (it can be different than `:7170`)

**Comment by c1tt1** [comment]
Thanks, I will write a demo example similar to the ones you wrote on the go client and fix the constructor parameter. 

I am just thinking of how to implement the mux as it's not straight forward to me, do you have any ideas on that?

**Comment by celrenheit** [comment]
The mux is not a necessity. It is just a high level test to have an easier consumption model similar to incoming request in go's `http.Handler`.
Maybe the thing that may be simplified is the consume part (https://github.com/celrenheit/sandglass-client/pull/2/files#diff-2e206c93740237b7dd70ae5571ab44aeR29), with an eventemitter or event generators (I don't if they are now available in node?)
```js
for (var msg of consumer.consume()) {
 // handle msg
}
```
If you have a better idea, I'd be happy to hear it

**Comment by c1tt1** [comment]
I know what you mean. The problem is that the way of iterating is synchronous, doesn’t work for asynchronous sources of data. Your example, in the above code, cannot deliver its data asynchronously. Asynchronous iteration is part of the next ECMAScript proposal.

The way to use it would be:

```js
consumer.consume()
  .then(msgs => {
    // do whatever you want with the messages
    for (const msg of msgs()) {
    // handle msg
    }
  })
  .catch(err => err)
```

or do the async await style:
```js
async function msgs() {
  const msgs = await consumer.consume()
  return msgs
}

// do whatever you want with the messages
for (const msg of msgs()) {
 // handle msg
}
```

**Comment by celrenheit** [comment]
You are saying both of the code samples you made are not available currently ?
If yes, then we cannot do nothing about it. It might be better to stick with just the raw grpc stream.

**Comment by celrenheit** [comment]
How about an API like this ?
```js
consumer.consume(function(msg) { // callback called for each message received })
.then(function() { // done successfully })
.catch(function(err) { // error })
```

**Comment by c1tt1** [comment]
It's the same as the one I wrote the only difference is the es6 syntax. For example:

```js
consumer.consume(function(msg) { // callback called for each message received })
.then(function() { // done successfully })
.catch(function(err) { // error })
```
is same as
```js
consumer.consume(msg => { // callback called for each message received })
.then(() => { // done successfully })
.catch(err => { // error })
```

I prefer the newer es6 syntax because it's cleaner.

**Comment by c1tt1** [comment]
```
You are saying both of the code samples you made are not available currently ?
If yes, then we cannot do nothing about it. It might be better to stick with just the raw grpc stream.
```
No I meant both examples are available. what's not available is asynchronous iteration.

**Comment by c1tt1** [comment]
There are a few issues with the grpc calls in `@sandglass/grpc` it seems `@sandglass/grpc` functions calls are made but there's an issue with parameter types, it looks like a serialisation issue.

**Comment by celrenheit** [comment]
I just checked this out, you have an error with arguejs. I think it is coming from the way ConsumeFromGroup is called here https://github.com/celrenheit/sandglass-client/pull/2/files#diff-2e206c93740237b7dd70ae5571ab44aeR38.
It returns a stream and does not accept a callback.
The following code should work:
```js
const sgproto = require('@sandglass/grpc')
const grpc = require('grpc')

let client = new sgproto.BrokerService(':7170', grpc.credentials.createInsecure())

let partitions = client.GetTopic({ name: "emails" }, (err, resp) => {
    let stream = client.ConsumeFromGroup({
        topic: "emails",
        partition: resp.partitions[0],
        consumerGroupName: "group1",
        consumerName: "name1",
      })
      stream.on('data', (msg) => {
        console.log(msg.value.toString())
      });
      stream.on('end', () => {
        console.log("done")
      });
      stream.on('error', (err) => {
        console.log("error", err)
      });
})
```

For producing 10 messages you can use this:
`sandctl produce emails '{"dest" : "hi@example.com"}' -n 10`

In the future, it might be better to use something like typescript to avoid issues like these

**Comment by celrenheit** [comment]
I noticed an issue in sandglass. After the first consumption if you consume again it should show nothing but 10 seconds later you will see them redelivered every time (if they are not acknowledged) indefinitely.
I'll fix this upstream by setting a limit to the number of re-deliveries.

**Comment by c1tt1** [comment]
I have push a consumer example but there's an issue when consuming the topics. Do you know what the `ErrPartitionNotFound` error is exactly?

**Comment by celrenheit** [comment]
Great!
The error means sandglass cannot find the requested partition.
Tell me if you want to add something more , otherwise I'll merge this.

**Comment by c1tt1** [comment]
I guess you can merge this for now. I will add more examples and readme if you agree

**Comment by celrenheit** [comment]
Great Thanks 👍

**Pull request merged**
